seed: 42
data:
    db_name: "ci_db"
    external_path: "data/external/"
    mag:
        query_values:
            [
                "crowdsourcing",
                "citizen science",
                "collective intelligence",
                "wisdom of crowds",
                "collective wisdom",
                "wisdom of the crowd",
                "social computing",
                "human computation",
            ]
        entity_name: "F.FN"
        metadata:
            [
                "Id",
                "Ti",
                "AA.AfId",
                "AA.AfN",
                "AA.AuId",
                "AA.DAuN",
                "AA.S",
                "CC",
                "D",
                "F.DFN",
                "F.FId",
                "J.JId",
                "J.JN",
                "Pt",
                "RId",
                "Y",
                "DOI",
                "PB",
                "BT",
                "IA",
                "C.CN",
                "C.CId",
                "DN",
                "S",
                "F.FN",
            ]
        with_doi: False
        mag_start_date: "2000-01-01"
        mag_end_date: "today"
        intervals_in_a_year: 6
        store_path: "data/external/mag_response"
fos_subset:
    [
        "deep learning",
        "machine learning",
        "reinforcement learning",
        "artificial intelligence",
    ]

affiliations:
    non_industry:
        [
            "park centre for mental health",
            "university",
            "foundation",
            "institution",
            "universidade",
            "institute",
            "commission",
            "agency",
            "department",
            "council",
            "college",
            "ministry",
            "universidad",
            "school",
            "international centre",
            "universiti",
            "hospital",
            "medical center",
            "united states fish and wildlife service",
            "centre",
            "center",
            "laboratory",
            "universiteti",
            "kantonsspital st gallen",
            "infirmary",
            "centro",
            "museum",
            "academy",
            "istituto",
            "national association",
            "conservation trust",
            "instituto",
            "ezemvelo kzn wildlife",
            "nhs trust",
            "universite",
            "society",
            "united states office of research integrity",
            "missouri botanical garden",
            "nhs lothian",
            "zurcher fachhochschule",
            "administration",
            "ecole",
            "congressional research service",
            "universitat",
            "bureau",
            "clinical trial service unit",
            "fachhochschule lubeck",
            "umass memorial health care",
            "penn state abington",
            "federation",
            "office of",
            "nhs greater glasgow and clyde",
            "intelligence and national security alliance",
            "rambam health care campus",
            "cancer research uk",
            "carolinas healthcare system",
            "arthritis research uk",
            "vancouver coastal health",
            "red cross",
            "commonwealth scientific and industrial",
            "institut",
            "academia",
            "association",
            "fondazione",
            "faculty",
            "escuela",
            "facultad de filosofia y letras",
            "coral reef alliance",
            "fundacion",
            "queensland health",
            "jamia millia islamia",
            "polytechnic",
            "united states forest service",
            "national ecological observatory network",
            "national guard health affairs",
            "geoscience australia",
            "statistics canada",
            "health service executive",
            "district",
            "national marrow donor program",
            "junta of andalusia",
            "american board of legal medicine",
            "geological survey of denmark and greenland",
            "australia bioinformatics resource",
            "south african weather service",
            "scottish national blood transfusion service",
            "pancreatic cancer action network",
            "va palo alto healthcare system",
            "swiss federal laboratories for materials",
            "defence research and development organisation",
            "conservation international",
            "european union",
            "clalit health services",
            "comision nacional",
            "departamento",
            "office national",
            "rajiv gandhi proudyogiki vishwavidyalaya",
            "nhs blood and transplant",
            "european molecular biology organization",
            "facultad",
            "united nations environment programme",
            "national health service",
            "rochester general health system",
            "bundesanstalt fur materialforschung und prufung",
            "drugs for neglected diseases initiative",
            "gundersen health system",
            "fisheries and oceans canada",
            "food safety and inspection service",
            "civil aviation authority of singapore",
            "union of concerned scientists",
            "california state water resources control board",
            "wright patterson air force base",
            "bioversity international",
            "marine scotland",
            "qatar national library",
            "american geophysical union",
            "cherokee nation",
            "national radio astronomy observatory",
            "asia pacific economic cooperation",
            "the leprosy mission international",
            "kenya wildlife service",
            "australian taxation office",
            "breast cancer now",
            "pan american health organization",
            "united states public health service",
            "butterfly conservation",
            "king abdulaziz medical city",
        ]

open_access:
    [
        "arxiv computation and language",
        "arxiv adaptation and self organizing systems",
        "arxiv artificial intelligence",
        "arxiv multiagent systems",
        "arxiv computational engineering finance and science",
        "arxiv neurons and cognition",
        "arxiv learning",
        "arxiv data analysis statistics and probability",
        "arxiv quantitative methods",
        "biorxiv",
        "arxiv computer vision and pattern recognition",
        "arxiv information theory",
        "arxiv signal processing",
        "arxiv sound",
        "arxiv image and video processing",
        "arxiv social and information networks",
        "arxiv materials science",
        "arxiv neural and evolutionary computing",
        "arxiv statistical mechanics",
        "arxiv networking and internet architecture",
        "arxiv machine learning",
        "arxiv high energy physics phenomenology",
        "arxiv software engineering",
        "arxiv molecular networks",
        "arxiv physics and society",
        "arxiv quantum physics",
        "arxiv applications",
        "arxiv cryptography and security",
        "arxiv robotics",
        "arxiv instrumentation and methods for astrophysics",
        "arxiv distributed parallel and cluster computing",
        "arxiv computational geometry",
        "arxiv statistical finance",
        "arxiv computers and society",
        "arxiv human computer interaction",
        "chemrxiv",
        "arxiv high energy astrophysical phenomena",
        "arxiv econometrics",
        "arxiv optimization and control",
        "arxiv computational physics",
        "arxiv atmospheric and oceanic physics",
        "arxiv genomics",
        "arxiv trading and market microstructure",
        "medrxiv",
        "arxiv disordered systems and neural networks",
        "arxiv computer science and game theory",
        "arxiv biomolecules",
        "arxiv strongly correlated electrons",
        "arxiv audio and speech processing",
        "arxiv cosmology and nongalactic astrophysics",
        "arxiv methodology",
        "arxiv multimedia",
        "arxiv data structures and algorithms",
        "arxiv databases",
        "arxiv digital libraries",
        "arxiv optics",
        "arxiv programming languages",
        "arxiv numerical analysis",
        "arxiv chemical physics",
        "arxiv fluid dynamics",
        "arxiv other computer science",
        "arxiv emerging technologies",
        "arxiv statistics theory",
        "arxiv medical physics",
        "arxiv other statistics",
        "arxiv logic in computer science",
        "arxiv information retrieval",
        "arxiv probability",
        "arxiv applied physics",
        "socarxiv",
        "arxiv mesoscale and nanoscale physics",
        "arxiv computational finance",
        "arxiv geophysics",
        "arxiv dynamical systems",
        "arxiv high energy physics lattice",
        "arxiv physics education",
        "arxiv astrophysics of galaxies",
        "arxiv risk management",
        "arxiv biological physics",
        "arxiv soft condensed matter",
        "arxiv solar and stellar astrophysics",
        "arxiv portfolio management",
        "arxiv instrumentation and detectors",
        "arxiv theoretical economics",
        "arxiv general economics",
        "arxiv high energy physics theory",
        "arxiv graphics",
        "arxiv populations and evolution",
        "arxiv general relativity and quantum cosmology",
        "arxiv mathematical finance",
        "arxiv earth and planetary astrophysics",
        "arxiv atomic and molecular clusters",
        "arxiv algebraic topology",
        "arxiv pattern formation and solitons",
        "arxiv general literature",
        "arxiv performance",
        "arxiv tissues and organs",
        "arxiv analysis of pdes",
        "arxiv general finance",
        "arxiv quantum gases",
        "arxiv superconductivity",
        "arxiv hardware architecture",
        "arxiv space physics",
        "arxiv pricing of securities",
        "arxiv mathematical software",
        "arxiv computation",
        "arxiv nuclear theory",
        "arxiv plasma physics",
        "arxiv combinatorics",
        "arxiv astrophysics",
        "arxiv cell behavior",
        "arxiv formal languages and automata theory",
        "arxiv computational complexity",
        "arxiv systems and control",
        "arxiv chaotic dynamics",
        "arxiv algebraic geometry",
        "arxiv category theory",
        "arxiv popular physics",
        "arxiv symbolic computation",
        "arxiv discrete mathematics",
        "arxiv accelerator physics",
        "arxiv other quantitative biology",
        "arxiv general physics",
        "arxiv classical analysis and odes",
        "arxiv high energy physics experiment",
        "arxiv economics",
        "arxiv group theory",
        "arxiv history and overview",
        "arxiv logic",
        "arxiv general topology",
        "arxiv functional analysis",
        "psyarxiv",
        "arxiv operating systems",
        "arxiv nuclear experiment",
        "arxiv number theory",
    ]
plots:
    fos_levels: [1, 2, 3, 4]
    top_n: 20
