data:
    mag:
        year: 2000
        metadata: ["Id", "Ti", "AA.AfId","AA.AfN","AA.AuId","AA.DAuN","AA.S","CC","D","F.DFN","F.FId","J.JId","J.JN","Pt","RId","Y","DOI","PB","BT","IA","F.FN"]
        fos: ["crowdsourcing", "citizen science", "collective intelligence", "wisdom of crowds", "collective wisdom", "wisdom of the crowd"]
        entity_name: 'F.FN'
        query_count: 1000
        store_path: 'data/external/mag_response'
    external:
        path: 'data/external/'
